#Practical 7: Market Basket Analysis
Harry Sangoi  25MBD021

In [1]:
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd

In [2]:
#Sample Dataset
dataset = [
    ['milk','bread','butter'],
    ['bread','butter','jam'],
    ['milk','bread','jam'],
    ['milk','bread','butter','jam'],
    ['butter','jam']
]

In [3]:
#Step 1: Preprocessing the data
te = TransactionEncoder() #Initialize Transaction Encoder
te_ary = te.fit_transform(dataset)#Transform the dataset into a binary matrix
df = pd.DataFrame(te_ary, columns=te.columns_)#Convert to a pandas DataFrame

In [4]:
#Step 2: Generate frequent itemsets using Apriori Algorithm
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#min_support is the threshold for itemset frequency(eg., 60%)

In [5]:
#Step 3: Generate association rules
#Calculate num_itemsets (total number of unique items)
num_itemsets = len(frequent_itemsets.itemsets[0])

#Now include num_itemsets in the association rules call
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7, num_itemsets=num_itemsets)

In [6]:
#Output results
print("Frequent Itemsets:")
print(frequent_itemsets)
print("\nAssociation Rules:")
print(rules)

Frequent Itemsets:
   support         itemsets
0      0.8          (bread)
1      0.8         (butter)
2      0.8            (jam)
3      0.6           (milk)
4      0.6  (bread, butter)
5      0.6     (jam, bread)
6      0.6    (milk, bread)
7      0.6    (jam, butter)

Association Rules:
  antecedents consequents  antecedent support  ...  jaccard  certainty  kulczynski
0     (bread)    (butter)                 0.8  ...     0.60     -0.250       0.750
1    (butter)     (bread)                 0.8  ...     0.60     -0.250       0.750
2       (jam)     (bread)                 0.8  ...     0.60     -0.250       0.750
3     (bread)       (jam)                 0.8  ...     0.60     -0.250       0.750
4      (milk)     (bread)                 0.6  ...     0.75      1.000       0.875
5     (bread)      (milk)                 0.8  ...     0.75      0.375       0.875
6       (jam)    (butter)                 0.8  ...     0.60     -0.250       0.750
7    (butter)       (jam)                 0.8  ...     0.60     -0.250       0.750

[8 rows x 14 columns]

In [7]:
frequent_itemsets

   support         itemsets
0      0.8          (bread)
1      0.8         (butter)
2      0.8            (jam)
3      0.6           (milk)
4      0.6  (bread, butter)
5      0.6     (jam, bread)
6      0.6    (milk, bread)
7      0.6    (jam, butter)

In [8]:
rules

  antecedents consequents  antecedent support  ...  jaccard  certainty  kulczynski
0     (bread)    (butter)                 0.8  ...     0.60     -0.250       0.750
1    (butter)     (bread)                 0.8  ...     0.60     -0.250       0.750
2       (jam)     (bread)                 0.8  ...     0.60     -0.250       0.750
3     (bread)       (jam)                 0.8  ...     0.60     -0.250       0.750
4      (milk)     (bread)                 0.6  ...     0.75      1.000       0.875
5     (bread)      (milk)                 0.8  ...     0.75      0.375       0.875
6       (jam)    (butter)                 0.8  ...     0.60     -0.250       0.750
7    (butter)       (jam)                 0.8  ...     0.60     -0.250       0.750

[8 rows x 14 columns]

##Using a CSV

In [24]:
import pandas as pd
import numpy as np
from apyori import apriori

In [25]:
df = pd.read_csv('Market_Basket_Optimisation.csv', header=None)

In [26]:
df.head()

              0          1           2   ...               17       18         19
0         shrimp    almonds     avocado  ...  frozen smoothie  spinach  olive oil
1        burgers  meatballs        eggs  ...              NaN      NaN        NaN
2        chutney        NaN         NaN  ...              NaN      NaN        NaN
3         turkey    avocado         NaN  ...              NaN      NaN        NaN
4  mineral water       milk  energy bar  ...              NaN      NaN        NaN

[5 rows x 20 columns]

In [27]:
df.isna().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [28]:
#Data Cleaning Step

#replacing empty value with 0
df.fillna(0, inplace=True)

In [29]:
df.head()

              0          1           2   ...               17       18         19
0         shrimp    almonds     avocado  ...  frozen smoothie  spinach  olive oil
1        burgers  meatballs        eggs  ...                0        0          0
2        chutney          0           0  ...                0        0          0
3         turkey    avocado           0  ...                0        0          0
4  mineral water       milk  energy bar  ...                0        0          0

[5 rows x 20 columns]

In [30]:
#Data Pre-Processing step

#for using aprori, need to convert data in list format
#transaction = [['apple','almonds'],['apple'],['banana','apple']]

transactions = []

for i in range(0,len(df)):
  transactions.append([str(df.values[i,j]) for j in range(0,20) if str(df.values[i,j])!='0'])

In [31]:
#Verifying by printing the 0th transaction
transactions[0]

['shrimp',
 'almonds',
 'avocado',
 'vegetables mix',
 'green grapes',
 'whole weat flour',
 'yams',
 'cottage cheese',
 'energy drink',
 'tomato juice',
 'low fat yogurt',
 'green tea',
 'honey',
 'salad',
 'mineral water',
 'salmon',
 'antioxydant juice',
 'frozen smoothie',
 'spinach',
 'olive oil']

In [32]:
#Verifying by printing the 1st transaction
transactions[1]

['burgers', 'meatballs', 'eggs']

In [33]:
#Call apriori function which requires minimum support, confidance and lift, min length is combination of item default is 2
rules = apriori(transactions, min_support=0.003, min_confidance = 0.2, min_lift = 3, min_length = 2)

min_support = 0.003 -> means selecting items with min support of 0.3%

min_confidance = 0.2 -> means min condifance of 20%

min_lift = 3

min_length = 2-> means no. of items in the transaction should be 2

In [34]:
#it generates a set of rules in a generator file
rules

In [35]:
#all rules need to be converted in a list
Results = list(rules)

In [36]:
Results[1]

RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken'}), items_add=frozenset({'light cream'}), confidence=0.07555555555555556, lift=4.843950617283951), OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)])

In [37]:
#Convert result in a dataframe for further operation
df_results = pd.DataFrame(Results)

In [38]:
df_results.head()

                              items  ...                                 ordered_statistics
0        (brownies, cottage cheese)  ...  [((brownies), (cottage cheese), 0.102766798418...
1            (light cream, chicken)  ...  [((chicken), (light cream), 0.0755555555555555...
2  (mushroom cream sauce, escalope)  ...  [((escalope), (mushroom cream sauce), 0.072268...
3                 (escalope, pasta)  ...  [((escalope), (pasta), 0.07394957983193277, 4....
4       (tomato juice, fresh bread)  ...  [((fresh bread), (tomato juice), 0.09907120743...

[5 rows x 3 columns]

In [39]:
support = df_results.support
#keeping a support in a separate data frame so we can use later

In [40]:
'''
convert orderstatistic in a proper format.
order statistic has lhs => rhs as well rhs => lhs
we can choose any one for convience.
Let's choose first one which is 'df_results['ordered_statistics'][i][0]'
'''

#all four empty list which will contain lhs, rhs, confidance and lift respectively

first_values = []
second_values = []
third_values = []
fourth_values = []

In [41]:
#Loop number of rows time and append 1 by 1 value in a separte list

for i in range(df_results.shape[0]):
  single_list = df_results['ordered_statistics'][i][0]
  first_values.append(list(single_list[0]))
  second_values.append(list(single_list[1]))
  third_values.append(single_list[2])
  fourth_values.append(single_list[3])

#first and second element was frozenset which needed to be converted into a list

In [42]:
#converting all the four list into dataframe for further operation
lhs = pd.DataFrame(first_values)
rhs = pd.DataFrame(second_values)

In [43]:
confidance = pd.DataFrame(third_values, columns=['Confidance'])
lift = pd.DataFrame(fourth_values, columns=['lift'])

In [44]:
#Concat all the list together in a single dataframe
df_final = pd.concat([lhs,rhs,support,confidance,lift], axis=1)

In [46]:
df_final.head()

             0     1                     0  ...   support Confidance      lift
0     brownies  None        cottage cheese  ...  0.003466   0.102767  3.225330
1      chicken  None           light cream  ...  0.004533   0.075556  4.843951
2     escalope  None  mushroom cream sauce  ...  0.005733   0.072269  3.790833
3     escalope  None                 pasta  ...  0.005866   0.073950  4.700812
4  fresh bread  None          tomato juice  ...  0.004266   0.099071  3.259356

[5 rows x 8 columns]

In [47]:
df_final.tail()

                0            1              0  ...   support Confidance      lift
89       pancakes  ground beef  mineral water  ...  0.003066   0.211009  3.532991
90    ground beef         None  mineral water  ...  0.003066   0.031208  3.344117
91      olive oil         None  mineral water  ...  0.003333   0.050607  3.216994
92  mineral water         milk      spaghetti  ...  0.003066   0.063889  3.014029
93       tomatoes         None  mineral water  ...  0.003333   0.048733  3.097846

[5 rows x 8 columns]


 we have some of place only 1 item in lhs and some place 3 or more so we need to a proper
 represenation for User to understand.
 replacing none with ' ' and combining three column's in 1
 example : coffee,none,none is converted to coffee, ,

In [49]:
df_final.fillna(value=' ', inplace=True)
df_final.head()

             0  1                     0  1  2   support  Confidance      lift
0     brownies           cottage cheese        0.003466    0.102767  3.225330
1      chicken              light cream        0.004533    0.075556  4.843951
2     escalope     mushroom cream sauce        0.005733    0.072269  3.790833
3     escalope                    pasta        0.005866    0.073950  4.700812
4  fresh bread             tomato juice        0.004266    0.099071  3.259356

In [50]:
#Set Column name
df_final.columns = ['lhs',1,'rhs',2,3,'support','confidance','lift']

In [51]:
df_final.head()

           lhs  1                   rhs  2  3   support  confidance      lift
0     brownies           cottage cheese        0.003466    0.102767  3.225330
1      chicken              light cream        0.004533    0.075556  4.843951
2     escalope     mushroom cream sauce        0.005733    0.072269  3.790833
3     escalope                    pasta        0.005866    0.073950  4.700812
4  fresh bread             tomato juice        0.004266    0.099071  3.259356

In [52]:
df_final['lhs'] = df_final['lhs'] + str(", ") + df_final[1]

In [53]:
df_final['rhs'] = df_final['rhs'] + str(", ") + df_final[2] + str(", ") + df_final[3]

In [54]:
df_final.head()

              lhs  1  ... confidance      lift
0     brownies,       ...   0.102767  3.225330
1      chicken,       ...   0.075556  4.843951
2     escalope,       ...   0.072269  3.790833
3     escalope,       ...   0.073950  4.700812
4  fresh bread,       ...   0.099071  3.259356

[5 rows x 8 columns]

In [55]:
#drop columns 1,2 and 3 because now we already appended to lhs column

df_final.drop(columns=[1,2,3], inplace=True)

In [56]:
#Final output
df_final.head()

              lhs                         rhs   support  confidance      lift
0     brownies,          cottage cheese,  ,    0.003466    0.102767  3.225330
1      chicken,             light cream,  ,    0.004533    0.075556  4.843951
2     escalope,    mushroom cream sauce,  ,    0.005733    0.072269  3.790833
3     escalope,                   pasta,  ,    0.005866    0.073950  4.700812
4  fresh bread,            tomato juice,  ,    0.004266    0.099071  3.259356

In [57]:
df_final.tail()

                      lhs  ...      lift
89  pancakes, ground beef  ...  3.532991
90         ground beef,    ...  3.344117
91           olive oil,    ...  3.216994
92    mineral water, milk  ...  3.014029
93            tomatoes,    ...  3.097846

[5 rows x 5 columns]

Top 10 items based on lift. Sortin desc order

In [58]:
df_final.sort_values('lift',ascending=False).head(10).reset_index()

   index                   lhs  ... confidance      lift
0     58          olive oil,    ...   0.058704  6.115863
1      6      fromage blanc,    ...   0.245098  5.164271
2     49        ground beef,    ...   0.031208  4.980600
3      1            chicken,    ...   0.075556  4.843951
4      3           escalope,    ...   0.073950  4.700812
5     28        ground beef,    ...   0.032564  4.697422
6     11              pasta,    ...   0.322034  4.506672
7     23        ground beef,    ...   0.040706  4.490183
8     69  frozen vegetables,    ...   0.033566  4.417225
9     10          olive oil,    ...   0.121457  4.122410

[10 rows x 6 columns]